In [1]:
import os
import sys
from pathlib import Path
BASE_DATA_PATH = os.path.join("..", "data", ".ipynb_checkpoints")
import pandas as pd
from sklearn.model_selection import train_test_split

sys.path.append(os.path.abspath(os.path.join('..')))
from utils.experiments import run_full_experiment_parallel, run_full_experiment

DATA_DIR = "../data/.ipynb_checkpoints/"
SPAM_DIR = "spambase"
COLLEGE_DIR = "college"
ELECTRICITY_DIR = "electricity"
EMPLOYEE_DIR = "employee"

In [11]:
datasets = [SPAM_DIR, ELECTRICITY_DIR, EMPLOYEE_DIR, COLLEGE_DIR]

### Spam dataset

In [12]:
SPAM_FOLDER = os.path.join(BASE_DATA_PATH, "spambase")
X_spam = pd.read_csv(os.path.join(SPAM_FOLDER, "X.csv"))
y_spam = pd.read_csv(os.path.join(SPAM_FOLDER, "y.csv")).iloc[:, 0]

In [ ]:
results_spam = run_full_experiment_parallel( X=X_spam, y=y_spam, dataset_name="Spam", missing_rates=[0.1, 0.3, 0.5, 0.8])

In [ ]:
results_spam.head()

,method,dataset,missing_schema,accuracy,balanced_accuracy,f1_score,roc_auc,missing_rate,fold,n_neighbors
0,Oracle,Spam,MCAR,0.914224,0.907551,0.889510,0.966053,0.1,0,NaN
1,Naive,Spam,MCAR,0.919653,0.913956,0.896936,0.967075,0.1,0,NaN
2,KNN_hard,Spam,MCAR,0.912052,0.904314,0.886076,0.966068,0.1,0,5.0
3,KNN_proba,Spam,MCAR,0.915309,0.907003,0.889831,0.965975,0.1,0,5.0
4,EM,Spam,MCAR,0.920738,0.914852,0.898187,0.966883,0.1,0,NaN

In [ ]:
results_spam.to_csv("../results/spam_results.csv")

### Electricity dataset

In [ ]:
ELECTRICITY_FOLDER = os.path.join(BASE_DATA_PATH, "electricity")
X_electricity = pd.read_csv(os.path.join(ELECTRICITY_FOLDER, "X.csv"))
y_electricity = pd.read_csv(os.path.join(ELECTRICITY_FOLDER, "y.csv")).iloc[:, 0]

In [ ]:
results_electricity = run_full_experiment_parallel( X=X_electricity, y=y_electricity, dataset_name="Electricity", missing_rates=[0.1, 0.3, 0.5, 0.8])

[INFO] Starting parallel execution for 80 tasks...

[Parallel(n_jobs=-1)]: Using backend LokyBackend with 10 concurrent workers.
[Parallel(n_jobs=-1)]: Done   5 tasks      | elapsed:  4.4min
[Parallel(n_jobs=-1)]: Done  12 tasks      | elapsed:  8.6min
[Parallel(n_jobs=-1)]: Done  21 tasks      | elapsed: 12.7min
[Parallel(n_jobs=-1)]: Done  30 tasks      | elapsed: 12.9min
[Parallel(n_jobs=-1)]: Done  41 tasks      | elapsed: 19.0min
[Parallel(n_jobs=-1)]: Done  52 tasks      | elapsed: 22.0min
[Parallel(n_jobs=-1)]: Done  70 out of  80 | elapsed: 24.6min remaining:  3.5min
[Parallel(n_jobs=-1)]: Done  80 out of  80 | elapsed: 26.7min finished

In [ ]:
results_electricity.head()

,method,dataset,missing_schema,accuracy,balanced_accuracy,f1_score,roc_auc,missing_rate,fold,n_neighbors
0,Oracle,Electricity,MCAR,0.751186,0.729743,0.667257,0.815952,0.1,0,NaN
1,Naive,Electricity,MCAR,0.751186,0.729539,0.666667,0.815973,0.1,0,NaN
2,KNN_hard,Electricity,MCAR,0.750083,0.728239,0.664693,0.815566,0.1,0,5.0
3,KNN_proba,Electricity,MCAR,0.749862,0.727843,0.663899,0.815628,0.1,0,5.0
4,EM,Electricity,MCAR,0.751186,0.729539,0.666667,0.815953,0.1,0,NaN

In [ ]:
results_electricity.to_csv("../results/electricity_results.csv")

### College dataset

In [2]:
COLLEGE_FOLDER = os.path.join(BASE_DATA_PATH, "college")
X_college = pd.read_csv(os.path.join(COLLEGE_FOLDER, "X.csv"))
y_college = pd.read_csv(os.path.join(COLLEGE_FOLDER, "y.csv")).iloc[:, 0]
X_college = X_college.astype(float)
y_college = y_college.astype(float)

In [5]:
results_college = run_full_experiment_parallel(X=X_college, y=y_college, dataset_name="College", missing_rates=[0.1, 0.3, 0.5, 0.8])

[INFO] Starting parallel execution for 80 tasks...

[Parallel(n_jobs=6)]: Using backend LokyBackend with 6 concurrent workers.
[Parallel(n_jobs=6)]: Done   1 tasks      | elapsed:  2.4min
[Parallel(n_jobs=6)]: Done   6 tasks      | elapsed:  2.5min
[Parallel(n_jobs=6)]: Done  13 tasks      | elapsed:  7.9min
[Parallel(n_jobs=6)]: Done  20 tasks      | elapsed: 11.1min
[Parallel(n_jobs=6)]: Done  29 tasks      | elapsed: 14.7min
[Parallel(n_jobs=6)]: Done  38 tasks      | elapsed: 19.8min
[Parallel(n_jobs=6)]: Done  49 tasks      | elapsed: 23.7min
[Parallel(n_jobs=6)]: Done  60 tasks      | elapsed: 26.2min
[Parallel(n_jobs=6)]: Done  78 out of  80 | elapsed: 29.6min remaining:   45.5s
[Parallel(n_jobs=6)]: Done  80 out of  80 | elapsed: 29.8min finished

In [8]:
results_college.head()

,method,dataset,missing_schema,accuracy,balanced_accuracy,f1_score,roc_auc,missing_rate,fold,n_neighbors
0,Oracle,College,MCAR,0.932237,0.818857,0.715008,0.958449,0.1,0,NaN
1,Naive,College,MCAR,0.932638,0.815059,0.713311,0.957164,0.1,0,NaN
2,KNN_hard,College,MCAR,0.930233,0.810996,0.704082,0.957293,0.1,0,5.0
3,KNN_proba,College,MCAR,0.933039,0.813947,0.713551,0.957492,0.1,0,5.0
4,EM,College,MCAR,0.932237,0.813487,0.711111,0.956907,0.1,0,NaN

In [7]:
results_college.to_csv("../results/college_results.csv")

### Employee turnover dataset

In [ ]:
EMPLOYEE_FOLDER = os.path.join(BASE_DATA_PATH, "employee_turnover")
X_employee = pd.read_csv(os.path.join(EMPLOYEE_FOLDER, "X.csv"))
Y_employee = pd.read_csv(os.path.join(EMPLOYEE_FOLDER, "Y.csv")).iloc[:, 0]

In [ ]:
results_employee = run_full_experiment_parallel( X=X_employee, y=Y_employee, dataset_name="Employee", missing_rates=[0.1, 0.3, 0.5, 0.8])

[INFO] Starting parallel execution for 80 tasks...

[Parallel(n_jobs=-1)]: Using backend LokyBackend with 10 concurrent workers.
[Parallel(n_jobs=-1)]: Done   5 tasks      | elapsed:  3.4min
[Parallel(n_jobs=-1)]: Done  12 tasks      | elapsed:  6.7min
[Parallel(n_jobs=-1)]: Done  21 tasks      | elapsed:  9.5min
[Parallel(n_jobs=-1)]: Done  30 tasks      | elapsed: 10.7min
[Parallel(n_jobs=-1)]: Done  41 tasks      | elapsed: 15.8min
[Parallel(n_jobs=-1)]: Done  52 tasks      | elapsed: 18.9min
[Parallel(n_jobs=-1)]: Done  70 out of  80 | elapsed: 21.7min remaining:  3.1min
[Parallel(n_jobs=-1)]: Done  80 out of  80 | elapsed: 22.9min finished

In [ ]:
results_employee.head()

,method,dataset,missing_schema,accuracy,balanced_accuracy,f1_score,roc_auc,missing_rate,fold,n_neighbors
0,Oracle,Employee,MCAR,0.985633,0.5,0.992765,0.663764,0.1,0,NaN
1,Naive,Employee,MCAR,0.985633,0.5,0.992765,0.664541,0.1,0,NaN
2,KNN_hard,Employee,MCAR,0.985633,0.5,0.992765,0.665636,0.1,0,5.0
3,KNN_proba,Employee,MCAR,0.985633,0.5,0.992765,0.665386,0.1,0,5.0
4,EM,Employee,MCAR,0.985633,0.5,0.992765,0.663689,0.1,0,NaN

In [ ]:
results_employee.to_csv("../results/employee_results.csv")