In [27]:
import os
import sys
from pathlib import Path
BASE_DATA_PATH = os.path.join("..", "data", ".ipynb_checkpoints")
import pandas as pd
from sklearn.model_selection import train_test_split

sys.path.append(os.path.abspath(os.path.join('..')))
from utils.experiments import run_full_experiment, run_full_experiment_parallel

DATA_DIR = "../data/.ipynb_checkpoints/"
SPAM_DIR = "spambase"
COLLEGE_DIR = "college"
ELECTRICITY_DIR = "electricity"
EMPLOYEE_DIR = "employee"

In [4]:
datasets = [SPAM_DIR, ELECTRICITY_DIR, EMPLOYEE_DIR, COLLEGE_DIR]

### Spam dataset

In [28]:
SPAM_FOLDER = os.path.join(BASE_DATA_PATH, "spambase")
X_spam = pd.read_csv(os.path.join(SPAM_FOLDER, "X.csv"))
y_spam = pd.read_csv(os.path.join(SPAM_FOLDER, "y.csv")).iloc[:, 0]

In [29]:
results_spam = run_full_experiment_parallel( X=X_spam, y=y_spam, dataset_name="Spam", missing_rates=[0.1, 0.3, 0.5, 0.8])

[INFO] Starting parallel execution for 80 tasks...

[Parallel(n_jobs=-1)]: Using backend LokyBackend with 10 concurrent workers.
[Parallel(n_jobs=-1)]: Done   5 tasks      | elapsed:  1.3min
[Parallel(n_jobs=-1)]: Done  12 tasks      | elapsed:  2.3min
[Parallel(n_jobs=-1)]: Done  21 tasks      | elapsed:  3.2min
[Parallel(n_jobs=-1)]: Done  30 tasks      | elapsed:  3.3min
[Parallel(n_jobs=-1)]: Done  41 tasks      | elapsed:  4.9min
[Parallel(n_jobs=-1)]: Done  52 tasks      | elapsed:  5.7min
[Parallel(n_jobs=-1)]: Done  70 out of  80 | elapsed:  6.3min remaining:   54.4s
[Parallel(n_jobs=-1)]: Done  80 out of  80 | elapsed:  6.9min finished

In [33]:
results_spam.head()

,method,dataset,missing_schema,accuracy,balanced_accuracy,f1_score,roc_auc,missing_rate,fold,n_neighbors
0,Oracle,Spam,MCAR,0.914224,0.907551,0.889510,0.966053,0.1,0,NaN
1,Naive,Spam,MCAR,0.919653,0.913956,0.896936,0.967075,0.1,0,NaN
2,KNN_hard,Spam,MCAR,0.912052,0.904314,0.886076,0.966068,0.1,0,5.0
3,KNN_proba,Spam,MCAR,0.915309,0.907003,0.889831,0.965975,0.1,0,5.0
4,EM,Spam,MCAR,0.920738,0.914852,0.898187,0.966883,0.1,0,NaN

In [32]:
results_spam.to_csv("../results/spam_results.csv")

### Electricity dataset

In [44]:
ELECTRICITY_FOLDER = os.path.join(BASE_DATA_PATH, "electricity")
X_electricity = pd.read_csv(os.path.join(ELECTRICITY_FOLDER, "X.csv"))
y_electricity = pd.read_csv(os.path.join(ELECTRICITY_FOLDER, "y.csv")).iloc[:, 0]

In [45]:
results_electricity = run_full_experiment_parallel( X=X_electricity, y=y_electricity, dataset_name="Electricity", missing_rates=[0.1, 0.3, 0.5, 0.8])

[INFO] Starting parallel execution for 80 tasks...

[Parallel(n_jobs=-1)]: Using backend LokyBackend with 10 concurrent workers.
[Parallel(n_jobs=-1)]: Done   5 tasks      | elapsed:  4.4min
[Parallel(n_jobs=-1)]: Done  12 tasks      | elapsed:  8.6min
[Parallel(n_jobs=-1)]: Done  21 tasks      | elapsed: 12.7min
[Parallel(n_jobs=-1)]: Done  30 tasks      | elapsed: 12.9min
[Parallel(n_jobs=-1)]: Done  41 tasks      | elapsed: 19.0min
[Parallel(n_jobs=-1)]: Done  52 tasks      | elapsed: 22.0min
[Parallel(n_jobs=-1)]: Done  70 out of  80 | elapsed: 24.6min remaining:  3.5min
[Parallel(n_jobs=-1)]: Done  80 out of  80 | elapsed: 26.7min finished

In [46]:
results_electricity.head()

,method,dataset,missing_schema,accuracy,balanced_accuracy,f1_score,roc_auc,missing_rate,fold,n_neighbors
0,Oracle,Electricity,MCAR,0.751186,0.729743,0.667257,0.815952,0.1,0,NaN
1,Naive,Electricity,MCAR,0.751186,0.729539,0.666667,0.815973,0.1,0,NaN
2,KNN_hard,Electricity,MCAR,0.750083,0.728239,0.664693,0.815566,0.1,0,5.0
3,KNN_proba,Electricity,MCAR,0.749862,0.727843,0.663899,0.815628,0.1,0,5.0
4,EM,Electricity,MCAR,0.751186,0.729539,0.666667,0.815953,0.1,0,NaN

In [47]:
results_electricity.to_csv("../results/electricity_results.csv")

### College dataset

In [18]:
COLLEGE_FOLDER = os.path.join(BASE_DATA_PATH, "college")
X_college = pd.read_csv(os.path.join(COLLEGE_FOLDER, "X.csv"))
y_college = pd.read_csv(os.path.join(COLLEGE_FOLDER, "y.csv")).iloc[:, 0]

### Employee turnover dataset

In [20]:
EMPLOYEE_FOLDER = os.path.join(BASE_DATA_PATH, "employee_turnover")
X_employee = pd.read_csv(os.path.join(EMPLOYEE_FOLDER, "X.csv"))
Y_employee = pd.read_csv(os.path.join(EMPLOYEE_FOLDER, "Y.csv")).iloc[:, 0]

In [52]:
results_employee = run_full_experiment_parallel( X=X_employee, y=Y_employee, dataset_name="Employee", missing_rates=[0.1, 0.3, 0.5, 0.8])

[INFO] Starting parallel execution for 80 tasks...

[Parallel(n_jobs=-1)]: Using backend LokyBackend with 10 concurrent workers.
[Parallel(n_jobs=-1)]: Done   5 tasks      | elapsed:  3.4min
[Parallel(n_jobs=-1)]: Done  12 tasks      | elapsed:  6.7min
[Parallel(n_jobs=-1)]: Done  21 tasks      | elapsed:  9.5min
[Parallel(n_jobs=-1)]: Done  30 tasks      | elapsed: 10.7min
[Parallel(n_jobs=-1)]: Done  41 tasks      | elapsed: 15.8min
[Parallel(n_jobs=-1)]: Done  52 tasks      | elapsed: 18.9min
[Parallel(n_jobs=-1)]: Done  70 out of  80 | elapsed: 21.7min remaining:  3.1min
[Parallel(n_jobs=-1)]: Done  80 out of  80 | elapsed: 22.9min finished

In [53]:
results_employee.head()

,method,dataset,missing_schema,accuracy,balanced_accuracy,f1_score,roc_auc,missing_rate,fold,n_neighbors
0,Oracle,Employee,MCAR,0.985633,0.5,0.992765,0.663764,0.1,0,NaN
1,Naive,Employee,MCAR,0.985633,0.5,0.992765,0.664541,0.1,0,NaN
2,KNN_hard,Employee,MCAR,0.985633,0.5,0.992765,0.665636,0.1,0,5.0
3,KNN_proba,Employee,MCAR,0.985633,0.5,0.992765,0.665386,0.1,0,5.0
4,EM,Employee,MCAR,0.985633,0.5,0.992765,0.663689,0.1,0,NaN

In [54]:
results_employee.to_csv("../results/employee_results.csv")

# Approach 1 (kNN with soft labels) and 2 (naive modeling)

### 5-fold stratified crossvalidation, with missing_rate = 0.2

In [3]:
missing_rate = 0.2

results = pd.DataFrame()

for dataset in datasets:
    print(dataset)
    X = pd.read_csv(os.path.join(DATA_DIR, dataset, "X.csv"))
    y = pd.read_csv(os.path.join(DATA_DIR, dataset, "Y.csv")).iloc[:, 0]
    df = run_cv_averaged(X, y, dataset, missing_rate)
    print(df)
    results = pd.concat([results, df], axis=0)

spambase
oracle method
1
2
3
4
5
MCAR
1
2
3
4
5
MAR1
1
2
3
4
5
MAR2
1
2
3
4
5
MNAR
1
2
3
4
5
                        method   dataset missing_schema n_neighbors  accuracy  \
0                       oracle  spambase              -           -  0.683762
1  unlabeled_log_reg_knn_proba  spambase           MCAR           5  0.605955
2               naive approach  spambase           MCAR        None  0.605955
3  unlabeled_log_reg_knn_proba  spambase           MAR1           5  0.605955
4               naive approach  spambase           MAR1        None  0.605955
5  unlabeled_log_reg_knn_proba  spambase           MAR2           5  0.605955
6               naive approach  spambase           MAR2        None  0.605955
7  unlabeled_log_reg_knn_proba  spambase           MNAR           5  0.605955
8               naive approach  spambase           MNAR        None  0.605955

   balanced_accuracy  f1_score   roc_auc
0           0.638196  0.512706  0.763256
1           0.500000  0.000000  0.500000
2           0.500000  0.000000  0.500000
3           0.500000  0.000000  0.500000
4           0.500000  0.000000  0.500000
5           0.500000  0.000000  0.500000
6           0.500000  0.000000  0.500000
7           0.500000  0.000000  0.500000
8           0.500000  0.000000  0.500000
electricity
oracle method
1

TypeError: unsupported operand type(s) for -: 'float' and 'str'

In [7]:
print(results)
results.to_csv('../results/results_spambase_missing02_neighbors5.csv', sep='\t', encoding='utf-8', index=False, header=True)

                        method   dataset missing_schema n_neighbors  accuracy  \
0                       oracle  spambase              -           -  0.683762
1  unlabeled_log_reg_knn_proba  spambase           MCAR           5  0.605955
2               naive approach  spambase           MCAR        None  0.605955
3  unlabeled_log_reg_knn_proba  spambase           MAR1           5  0.605955
4               naive approach  spambase           MAR1        None  0.605955
5  unlabeled_log_reg_knn_proba  spambase           MAR2           5  0.605955
6               naive approach  spambase           MAR2        None  0.605955
7  unlabeled_log_reg_knn_proba  spambase           MNAR           5  0.605955
8               naive approach  spambase           MNAR        None  0.605955

   balanced_accuracy  f1_score   roc_auc
0           0.638196  0.512706  0.763256
1           0.500000  0.000000  0.500000
2           0.500000  0.000000  0.500000
3           0.500000  0.000000  0.500000
4           0.500000  0.000000  0.500000
5           0.500000  0.000000  0.500000
6           0.500000  0.000000  0.500000
7           0.500000  0.000000  0.500000
8           0.500000  0.000000  0.500000